Movie page
Hannes-HH/capstone-project pull request #6
Opened 2021-05-10 11:04 UTC by Hannes-HH

Hi guys, thank you for your review. My movie page is finish now. 

+ fetching movie data by genre 
+ implement custom pagination 
+ create cards for the movie page 
+ implement functions to add and remove movies by genre

2021-05-10 16:09 UTC, namirsab requested changes
Hey @Hannes-HH! Your app is looking nice!
I've seen a few things that you can improve. Please take a look!

2021-05-10 16:09 UTC, namirsab commented on src/components/Pages/Movies/Movies.js
> +  // const fetchMovies = async () => {
Please remove commented code

2021-05-10 16:09 UTC, namirsab commented on src/components/Pages/Movies/Movies.js
> +        setGenres={setGenres}
It's not a good practice to pass the `setState` functions directly to children.
Insetad, the children should receive a prop `onGenreSelected` that then the parent (this component) would handle and change the state then.
When a `genre` is selected, this component would:
* set the selected genres accordingly
* set the page to be the first one.

2021-05-10 16:09 UTC, namirsab commented on src/components/Pages/Movies/Movies.js
> +      {numOfPages > 1 && (
Very good! conditional rendering well applied here :)

2021-05-10 16:09 UTC, namirsab commented on src/components/Pages/Movies/Movies.js
> +// 1e37d8deae00c9b519356f5d9412edbb
hm, what's that ?

2021-05-10 16:09 UTC, namirsab commented on src/hooks/useGenre.js
> +const useGenre = (selectedGenres) => {
Good intention here to create a custom hook, but:

* A custom hook should use hooks inside it's function body.
* If that's not the case, then this is not a hook, just a utility function that given an array of genres, get's you back a string of genre ids

I'd move this to a utilities folder, and change the name to something like `getGenresIdsAsString` or something like that.

2021-05-10 16:09 UTC, namirsab commented on src/hooks/useGenre.js
> +  const GenreIds = selectedGenres.map((g) => g.id);
`GenreIds` should be `genreIds`.
Remember, for variables we use `camelCase`

2021-05-10 16:09 UTC, namirsab commented on src/components/Genres/Genres.js
> +  useEffect(() => {
If you would move the state up to the parent component, this `useEffect` should be done there.

2021-05-10 16:09 UTC, namirsab commented on src/components/Genres/Genres.js
> +    <div style={{ padding: "6px 0" }}>
No inline styling please. Add a `className` and use CSS

2021-05-10 16:09 UTC, namirsab commented on src/components/Genres/Genres.js
> +          style={{ margin: 2 }}
Same here, even with material-ui you can use classes and CSS:
https://material-ui.com/customization/components/

2021-05-11 08:25 UTC, Hannes-HH commented on src/components/Pages/Movies/Movies.js
> +  // const fetchMovies = async () => {
Removed.

2021-05-11 08:26 UTC, Hannes-HH commented on src/components/Pages/Movies/Movies.js
> +// 1e37d8deae00c9b519356f5d9412edbb
Removed.

2021-05-11 09:31 UTC, Hannes-HH commented on src/components/Pages/Movies/Movies.js
> +        setGenres={setGenres}
The children received a prop onGenreSelected with an event handler.

2021-05-11 10:02 UTC, Hannes-HH commented on src/hooks/useGenre.js
> +const useGenre = (selectedGenres) => {
I removed the folder name to your suggestion.

2021-05-11 10:11 UTC, Hannes-HH commented on src/hooks/useGenre.js
> +  const GenreIds = selectedGenres.map((g) => g.id);
I changed in genreIds.

2021-05-11 14:08 UTC, Hannes-HH commented on src/components/Genres/Genres.js
> +    <div style={{ padding: "6px 0" }}>
The inline styling is removed.

2021-05-11 14:08 UTC, Hannes-HH commented on src/components/Genres/Genres.js
> +          style={{ margin: 2 }}
The inline styling is removed.

2021-05-11 14:47 UTC, Hannes-HH commented on src/components/Genres/Genres.js
> +  useEffect(() => {
Namir, I don't know what do you mean. Please let's talk about.

2021-05-12 08:35 UTC, merged